spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
    generate-ddl: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${BLOG_SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: ${BLOG_SPRING_DATASOURCE_URL}
    username: ${BLOG_SPRING_DATASOURCE_USERNAME}
    password: ${BLOG_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver # Inclusion ensures the JUnit test passes https://stackoverflow.com/a/31781524
